// SPDX-FileCopyrightText: 2025 QuantumHole <QuantumHole@github.com>
//
// SPDX-License-Identifier: GPL-3.0-or-later

#ifndef ACTION_H
#define ACTION_H

typedef enum
{
	ACTION_NONE,
	ACTION_BACK,
	ACTION_DESKTOP,
	ACTION_DESKTOP_WINDOW,
	ACTION_DIRECTORY_SELECT,
	ACTION_FILE_SELECT,
	ACTION_FILE_DELETE,
	ACTION_FILE_OPEN,
	ACTION_PLAY_BACKWARD,
	ACTION_PLAY_FORWARD,
	ACTION_PLAY_NEXT,
	ACTION_PLAY_PAUSE,
	ACTION_PLAY_PLAY,
	ACTION_PLAY_POSITION,
	ACTION_PLAY_PREVIOUS,
	ACTION_POWER,
	ACTION_PROJECT_CUBE,
	ACTION_PROJECT_CYLINDER,
	ACTION_PROJECT_FISHEYE,
	ACTION_PROJECT_FLAT,
	ACTION_PROJECT_SPHERE,
	ACTION_SETTINGS,
	ACTION_TILE_CUBE_MONO,
	ACTION_TILE_CUBE_STEREO,
	ACTION_TILE_LEFT_RIGHT,
	ACTION_TILE_MONO,
	ACTION_TILE_TOP_BOTTOM,
	ACTION_FLAG_MONO,
	ACTION_FLAG_STRETCH,
	ACTION_FLAG_SWITCH_EYES,
	ACTION_PARAM_ANGLE,
	ACTION_PARAM_ZOOM,
	ACTION_VOLUME
}
action_t;

#endif
